### ISSUE TITLE
Fix README.md Shields.io badges

### ISSUE THREAD

**Issue by gbowne1** [taotnpwaft/.github#1]
- [ ] Add Twitch Channel link shield
- [ ] Fix the 5 Sields below the allcontributors bot shield which relate to the GitHub repository.

This particular .github repo apparently is a GitHub secret and makes this README.md file gobal across the entire organization repository.

**Comment by gbowne1** [comment]
I think most of the issues are with these:

<img src="https://img.shields.io/github/discussions/taotnpwaft?style=for-the-badge">
<img src="https://img.shields.io/github/license/taotnpwaft?style=for-the-badge">
<img src="https://img.shields.io/github/contributors/taotnpwaft?style=for-the-badge">
<img src="https://img.shields.io/github/issues/taotnpwaft?style=for-the-badge">

Only the Org Stars shield appears.

**Comment by gbowne1** [comment]
@hitblast 

Have any ideas here?

**Comment by hitblast** [comment]
> @hitblast
> 
> Have any ideas here?

I'll try checking the source for the badges.

**Comment by gbowne1** [comment]
I think your changes should fix it.  I also don't know why there's two README.md..

I noticed when I had one on this repo project.. it still claimed to want another.  

I am certain that this .github project is global and puts the readme on all projects in the entire repo.

Bug in GitHub?

**Comment by hitblast** [comment]
> I think your changes should fix it. I also don't know why there's two README.md..
> 
> I noticed when I had one on this repo project.. it still claimed to want another.
> 
> I am certain that this .github project is global and puts the readme on all projects in the entire repo.
> 
> Bug in GitHub?

Well, not necessarily a bug, you can just skip over adding the README.md that's in the root. The README.md that is being used in this repository is actually the one that resides in `.github/profile/` :)

**Comment by gbowne1** [comment]
Hmm.. ok.  No need for two in this .github then.  

I am still learning the ins and outs of GitHub especially Org mode.  

I recall it saying something about .github/profile/ but wasn't sure.

**Comment by hitblast** [comment]
> Hmm.. ok. No need for two in this .github then.
> 
> I am still learning the ins and outs of GitHub especially Org mode.
> 
> I recall it saying something about .github/profile/ but wasn't sure.

Okay so, I went through the markdown and then revised on how shields actually work. The shields that show a question symbol instead of the expected content have a missing parameter. In order for some shields to work, there's a common pattern of parameters that go like this: `/:user/:repo` 

However, in the case of this markdown, only the `user` parameter has been passed for most of them, so they end up showing either a 404 error or something blank (the question symbol as mentioned before).

Any thoughts?

**Comment by gbowne1** [comment]
Yeah, I wasn't sure about how this works 100% on the org.  It worked fine when this was part of my personal repository @ gbowne1/taotnpwaft/

Sounds about right to me, though.

**Comment by gbowne1** [comment]
@hitblast  Still not working correctly.  I think some only work per project. So the shield link has to be different for each README.md  

I.e, /website would get its own badge or shield links on that repo project.  

Stars shield only works with GitHubOrg the way.  I am not sure how it would show individual stars for but the one for GitHub Org. Mode is the only Github badge/shield woking.. othee than the badges/shields below all that.

Thoughts?

**Comment by gbowne1** [comment]
Since there is no more Facebook Group, the groups link needs removed.
